// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	kafka "github.com/confluentinc/confluent-kafka-go/kafka"
	mock "github.com/stretchr/testify/mock"
)

// ProducerContainer is an autogenerated mock type for the ProducerContainer type
type ProducerContainer struct {
	mock.Mock
}

// ProduceAsync provides a mock function with given fields: message, headers, topic
func (_m *ProducerContainer) ProduceAsync(message []byte, headers []kafka.Header, topic string) error {
	ret := _m.Called(message, headers, topic)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []kafka.Header, string) error); ok {
		r0 = rf(message, headers, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
